export const ALL_RECIPE_REQUEST = "ALL_RECIPE_REQUEST";
export const ALL_RECIPE_SUCCESS = "ALL_RECIPE_SUCCESS";
export const ALL_RECIPE_FAIL = "ALL_RECIPE_FAIL";

export const RECIPE_DETAILS_REQUEST = "RECIPE_DETAILS_REQUEST";
export const RECIPE_DETAILS_SUCCESS = "RECIPE_DETAILS_SUCCESS";
export const RECIPE_DETAILS_FAIL = "RECIPE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";