export const ALL_RECIPE_REQUEST = "ALL_RECIPE_REQUEST";
export const ALL_RECIPE_SUCCESS = "ALL_RECIPE_SUCCESS";
export const ALL_RECIPE_FAIL = "ALL_RECIPE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";